files = [
    "Monsters/Aboleth.md",
    "Monsters/Adult Black Dragon.md",
    "Monsters/Adult Blue Dragon.md",
    "Monsters/Adult Brass Dragon.md",
    "Monsters/Adult Bronze Dragon.md",
    "Monsters/Adult Copper Dragon.md",
    "Monsters/Adult Gold Dragon.md",
    "Monsters/Adult Green Dragon.md",
    "Monsters/Adult Red Dragon.md",
    "Monsters/Adult Silver Dragon.md",
    "Monsters/Adult White Dragon.md",
    "Monsters/Air Elemental.md",
    "Monsters/Allosaurus.md",
    "Monsters/Ancient Black Dragon.md",
    "Monsters/Ancient Blue Dragon.md",
    "Monsters/Ancient Brass Dragon.md",
    "Monsters/Ancient Bronze Dragon.md",
    "Monsters/Ancient Copper Dragon.md",
    "Monsters/Ancient Gold Dragon.md",
    "Monsters/Ancient Green Dragon.md",
    "Monsters/Ancient Red Dragon.md",
    "Monsters/Ancient Silver Dragon.md",
    "Monsters/Ancient White Dragon.md",
    "Monsters/Animated Armor.md",
    "Monsters/Animated Flying Sword.md",
    "Monsters/Animated Rug of Smothering.md",
    "Monsters/Ankheg.md",
    "Monsters/Ankylosaurus.md",
    "Monsters/Ape.md",
    "Monsters/Archelon.md",
    "Monsters/Archmage.md",
    "Monsters/Assassin.md",
    "Monsters/Awakened Shrub.md",
    "Monsters/Awakened Tree.md",
    "Monsters/Axe Beak.md",
    "Monsters/Azer Sentinel.md",
    "Monsters/Baboon.md",
    "Monsters/Badger.md",
    "Monsters/Balor.md",
    "Monsters/Bandit Captain.md",
    "Monsters/Bandit.md",
    "Monsters/Barbed Devil.md",
    "Monsters/Basilisk.md",
    "Monsters/Bat.md",
    "Monsters/Bearded Devil.md",
    "Monsters/Behir.md",
    "Monsters/Berserker.md",
    "Monsters/Black Bear.md",
    "Monsters/Black Dragon Wyrmling.md",
    "Monsters/Black Pudding.md",
    "Monsters/Blink Dog.md",
    "Monsters/Blood Hawk.md",
    "Monsters/Blue Dragon Wyrmling.md",
    "Monsters/Boar.md",
    "Monsters/Bone Devil.md",
    "Monsters/Brass Dragon Wyrmling.md",
    "Monsters/Bronze Dragon Wyrmling.md",
    "Monsters/Brown Bear.md",
    "Monsters/Bugbear Stalker.md",
    "Monsters/Bugbear Warrior.md",
    "Monsters/Bulette.md",
    "Monsters/Camel.md",
    "Monsters/Cat.md",
    "Monsters/Centaur Trooper.md",
    "Monsters/Chain Devil.md",
    "Monsters/Chimera.md",
    "Monsters/Chuul.md",
    "Monsters/Clay Golem.md",
    "Monsters/Cloaker.md",
    "Monsters/Cloud Giant.md",
    "Monsters/Cockatrice.md",
    "Monsters/Commoner.md",
    "Monsters/Constrictor Snake.md",
    "Monsters/Copper Dragon Wyrmling.md",
    "Monsters/Couatl.md",
    "Monsters/Crab.md",
    "Monsters/Crocodile.md",
    "Monsters/Cultist Fanatic.md",
    "Monsters/Cultist.md",
    "Monsters/Darkmantle.md",
    "Monsters/Death Dog.md",
    "Monsters/Deer.md",
    "Monsters/Deva.md",
    "Monsters/Dire Wolf.md",
    "Monsters/Djinni.md",
    "Monsters/Doppelganger.md",
    "Monsters/Draft Horse.md",
    "Monsters/Dragon Turtle.md",
    "Monsters/Dretch.md",
    "Monsters/Drider.md",
    "Monsters/Druid.md",
    "Monsters/Dryad.md",
    "Monsters/Dust Mephit.md",
    "Monsters/Eagle.md",
    "Monsters/Earth Elemental.md",
    "Monsters/Efreeti.md",
    "Monsters/Elephant.md",
    "Monsters/Elk.md",
    "Monsters/Erinyes.md",
    "Monsters/Ettercap.md",
    "Monsters/Ettin.md",
    "Monsters/Fire Elemental.md",
    "Monsters/Fire Giant.md",
    "Monsters/Flesh Golem.md",
    "Monsters/Flying Snake.md",
    "Monsters/Frog.md",
    "Monsters/Frost Giant.md",
    "Monsters/Gargoyle.md",
    "Monsters/Gelatinous Cube.md",
    "Monsters/Ghast.md",
    "Monsters/Ghost.md",
    "Monsters/Ghoul.md",
    "Monsters/Giant Ape.md",
    "Monsters/Giant Badger.md",
    "Monsters/Giant Bat.md",
    "Monsters/Giant Boar.md",
    "Monsters/Giant Centipede.md",
    "Monsters/Giant Constrictor Snake.md",
    "Monsters/Giant Crab.md",
    "Monsters/Giant Crocodile.md",
    "Monsters/Giant Eagle.md",
    "Monsters/Giant Elk.md",
    "Monsters/Giant Fire Beetle.md",
    "Monsters/Giant Frog.md",
    "Monsters/Giant Goat.md",
    "Monsters/Giant Hyena.md",
    "Monsters/Giant Lizard.md",
    "Monsters/Giant Octopus.md",
    "Monsters/Giant Owl.md",
    "Monsters/Giant Rat.md",
    "Monsters/Giant Scorpion.md",
    "Monsters/Giant Seahorse.md",
    "Monsters/Giant Shark.md",
    "Monsters/Giant Spider.md",
    "Monsters/Giant Toad.md",
    "Monsters/Giant Venomous Snake.md",
    "Monsters/Giant Vulture.md",
    "Monsters/Giant Wasp.md",
    "Monsters/Giant Weasel.md",
    "Monsters/Giant Wolf Spider.md",
    "Monsters/Gibbering Mouther.md",
    "Monsters/Glabrezu.md",
    "Monsters/Gladiator.md",
    "Monsters/Gnoll Warrior.md",
    "Monsters/Goat.md",
    "Monsters/Goblin Boss.md",
    "Monsters/Goblin Minion.md",
    "Monsters/Goblin Warrior.md",
    "Monsters/Gold Dragon Wyrmling.md",
    "Monsters/Gorgon.md",
    "Monsters/Gray Ooze.md",
    "Monsters/Green Dragon Wyrmling.md",
    "Monsters/Green Hag.md",
    "Monsters/Grick.md",
    "Monsters/Griffon.md",
    "Monsters/Grimlock.md",
    "Monsters/Guard Captain.md",
    "Monsters/Guard.md",
    "Monsters/Guardian Naga.md",
    "Monsters/Half-Dragon.md",
    "Monsters/Harpy.md",
    "Monsters/Hawk.md",
    "Monsters/Hell Hound.md",
    "Monsters/Hezrou.md",
    "Monsters/Hill Giant.md",
    "Monsters/Hippogriff.md",
    "Monsters/Hippopotamus.md",
    "Monsters/Hobgoblin Captain.md",
    "Monsters/Hobgoblin Warrior.md",
    "Monsters/Homunculus.md",
    "Monsters/Horned Devil.md",
    "Monsters/Hunter Shark.md",
    "Monsters/Hydra.md",
    "Monsters/Hyena.md",
    "Monsters/Ice Devil.md",
    "Monsters/Ice Mephit.md",
    "Monsters/Imp.md",
    "Monsters/Incubus.md",
    "Monsters/Invisible Stalker.md",
    "Monsters/Iron Golem.md",
    "Monsters/Jackal.md",
    "Monsters/Killer Whale.md",
    "Monsters/Knight.md",
    "Monsters/Kobold Warrior.md",
    "Monsters/Kraken.md",
    "Monsters/Lamia.md",
    "Monsters/Lemure.md",
    "Monsters/Lich.md",
    "Monsters/Lion.md",
    "Monsters/Lizard.md",
    "Monsters/Mage.md",
    "Monsters/Magma Mephit.md",
    "Monsters/Magmin.md",
    "Monsters/Mammoth.md",
    "Monsters/Manticore.md",
    "Monsters/Marilith.md",
    "Monsters/Mastiff.md",
    "Monsters/Medusa.md",
    "Monsters/Merfolk Skirmisher.md",
    "Monsters/Merrow.md",
    "Monsters/Mimic.md",
    "Monsters/Minotaur Skeleton.md",
    "Monsters/Minotaur of Baphomet.md",
    "Monsters/Mule.md",
    "Monsters/Mummy Lord.md",
    "Monsters/Mummy.md",
    "Monsters/Nalfeshnee.md",
    "Monsters/Night Hag.md",
    "Monsters/Nightmare.md",
    "Monsters/Noble.md",
    "Monsters/Ochre Jelly.md",
    "Monsters/Octopus.md",
    "Monsters/Ogre Zombie.md",
    "Monsters/Ogre.md",
    "Monsters/Oni.md",
    "Monsters/Otyugh.md",
    "Monsters/Owl.md",
    "Monsters/Owlbear.md",
    "Monsters/Panther.md",
    "Monsters/Pegasus.md",
    "Monsters/Phase Spider.md",
    "Monsters/Piranha.md",
    "Monsters/Pirate Captain.md",
    "Monsters/Pirate.md",
    "Monsters/Pit Fiend.md",
    "Monsters/Planetar.md",
    "Monsters/Plesiosaurus.md",
    "Monsters/Polar Bear.md",
    "Monsters/Pony.md",
    "Monsters/Priest Acolyte.md",
    "Monsters/Priest.md",
    "Monsters/Pseudodragon.md",
    "Monsters/Pteranodon.md",
    "Monsters/Purple Worm.md",
    "Monsters/Quasit.md",
    "Monsters/Rakshasa.md",
    "Monsters/Rat.md",
    "Monsters/Raven.md",
    "Monsters/Red Dragon Wyrmling.md",
    "Monsters/Reef Shark.md",
    "Monsters/Remorhaz.md",
    "Monsters/Rhinoceros.md",
    "Monsters/Riding Horse.md",
    "Monsters/Roc.md",
    "Monsters/Roper.md",
    "Monsters/Rust Monster.md",
    "Monsters/Saber-Toothed Tiger.md",
    "Monsters/Sahuagin Warrior.md",
    "Monsters/Salamander.md",
    "Monsters/Satyr.md",
    "Monsters/Scorpion.md",
    "Monsters/Scout.md",
    "Monsters/Sea Hag.md",
    "Monsters/Seahorse.md",
    "Monsters/Shadow.md",
    "Monsters/Shambling Mound.md",
    "Monsters/Shield Guardian.md",
    "Monsters/Shrieker Fungus.md",
    "Monsters/Silver Dragon Wyrmling.md",
    "Monsters/Skeleton.md",
    "Monsters/Solar.md",
    "Monsters/Specter.md",
    "Monsters/Sphinx of Lore.md",
    "Monsters/Sphinx of Valor.md",
    "Monsters/Sphinx of Wonder.md",
    "Monsters/Spider.md",
    "Monsters/Spirit Naga.md",
    "Monsters/Sprite.md",
    "Monsters/Spy.md",
    "Monsters/Steam Mephit.md",
    "Monsters/Stirge.md",
    "Monsters/Stone Giant.md",
    "Monsters/Stone Golem.md",
    "Monsters/Storm Giant.md",
    "Monsters/Succubus.md",
    "Monsters/Swarm of Bats.md",
    "Monsters/Swarm of Crawling Claws.md",
    "Monsters/Swarm of Insects.md",
    "Monsters/Swarm of Piranhas.md",
    "Monsters/Swarm of Rats.md",
    "Monsters/Swarm of Ravens.md",
    "Monsters/Swarm of Venomous Snakes.md",
    "Monsters/Tarrasque.md",
    "Monsters/Tiger.md",
    "Monsters/Tough Boss.md",
    "Monsters/Tough.md",
    "Monsters/Treant.md",
    "Monsters/Triceratops.md",
    "Monsters/Troll Limb.md",
    "Monsters/Troll.md",
    "Monsters/Tyrannosaurus Rex.md",
    "Monsters/Unicorn.md",
    "Monsters/Vampire Familiar.md",
    "Monsters/Vampire Spawn.md",
    "Monsters/Vampire.md",
    "Monsters/Venomous Snake.md",
    "Monsters/Violet Fungus.md",
    "Monsters/Vrock.md",
    "Monsters/Vulture.md",
    "Monsters/Warhorse Skeleton.md",
    "Monsters/Warhorse.md",
    "Monsters/Warrior Infantry.md",
    "Monsters/Warrior Veteran.md",
    "Monsters/Water Elemental.md",
    "Monsters/Weasel.md",
    "Monsters/Werebear.md",
    "Monsters/Wereboar.md",
    "Monsters/Wererat.md",
    "Monsters/Weretiger.md",
    "Monsters/Werewolf.md",
    "Monsters/White Dragon Wyrmling.md",
    "Monsters/Wight.md",
    "Monsters/Will-o'-Wisp.md",
    "Monsters/Winter Wolf.md",
    "Monsters/Wolf.md",
    "Monsters/Worg.md",
    "Monsters/Wraith.md",
    "Monsters/Wyvern.md",
    "Monsters/Xorn.md",
    "Monsters/Young Black Dragon.md",
    "Monsters/Young Blue Dragon.md",
    "Monsters/Young Brass Dragon.md",
    "Monsters/Young Bronze Dragon.md",
    "Monsters/Young Copper Dragon.md",
    "Monsters/Young Gold Dragon.md",
    "Monsters/Young Green Dragon.md",
    "Monsters/Young Red Dragon.md",
    "Monsters/Young Silver Dragon.md",
    "Monsters/Young White Dragon.md",
    "Monsters/Zombie.md",
]
